# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

invkernel_cpp <- function(z, w, mymat, parameters) {
    .Call(`_CausalStump_invkernel_cpp`, z, w, mymat, parameters)
}

mu_solution_cpp <- function(y, z, invKmat, parameters) {
    .Call(`_CausalStump_mu_solution_cpp`, y, z, invKmat, parameters)
}

kernmat_GP_SE_cpp <- function(X1, X2, Z1, Z2, para) {
    .Call(`_CausalStump_kernmat_GP_SE_cpp`, X1, X2, Z1, Z2, para)
}

grad_GP_SE_cpp <- function(y, X, z, w, Kmat, Km, Ka, invKmatn, parameters) {
    .Call(`_CausalStump_grad_GP_SE_cpp`, y, X, z, w, Kmat, Km, Ka, invKmatn, parameters)
}

stats_GP_SE <- function(y, Kmat, invKmatn, parameters) {
    .Call(`_CausalStump_stats_GP_SE`, y, Kmat, invKmatn, parameters)
}

kernmat_TP_SE_cpp <- function(X1, X2, Z1, Z2, para) {
    .Call(`_CausalStump_kernmat_TP_SE_cpp`, X1, X2, Z1, Z2, para)
}

grad_TP_SE_cpp <- function(y, X, z, w, Smat, Sm, Sa, invSmatn, parameters) {
    .Call(`_CausalStump_grad_TP_SE_cpp`, y, X, z, w, Smat, Sm, Sa, invSmatn, parameters)
}

stats_TP_SE <- function(y, Kmat, invKmatn, parameters) {
    .Call(`_CausalStump_stats_TP_SE`, y, Kmat, invKmatn, parameters)
}

Nesterov_cpp <- function(learn_rate, momentum, nu, grad, para) {
    .Call(`_CausalStump_Nesterov_cpp`, learn_rate, momentum, nu, grad, para)
}

Nadam_cpp <- function(iter, learn_rate, beta1, beta2, eps, m, v, grad, para) {
    .Call(`_CausalStump_Nadam_cpp`, iter, learn_rate, beta1, beta2, eps, m, v, grad, para)
}

Adam_cpp <- function(iter, learn_rate, beta1, beta2, eps, m, v, grad, para) {
    .Call(`_CausalStump_Adam_cpp`, iter, learn_rate, beta1, beta2, eps, m, v, grad, para)
}

